In [16]:
#Syntax TensorFlow
# import tensorflow as tf, la v2 no tiene session
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()



In [14]:
#creamos un msg sera una cte con una cadena de caracteres.
msg1 = tf.constant("Hellowo")
msg2 = tf.constant(" tensorasd")

In [10]:
#si hago print, nos dira que es un tensor tipo sprint
print(msg1)
print(type(msg1))

Tensor("Const:0", shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.Tensor'>


In [15]:
#Para concatenar tenemos que usar una session dentro de tf, como sesion, el resultado es ejecutar la sesion msg1+msg2
#Asi se ejecutan cosas dentro de tf, dentro de una sesion
with tf.Session() as sesion:
  resultado = sesion.run(msg1 + msg2)
resultado  

b'Hellowo tensorasd'

In [21]:
#Ahora con int's, hago una sesion para sumar....
a = tf.constant(10)
b = tf.constant(5)

with tf.Session() as sesion:
  suma = sesion.run(a+b)
  resta = sesion.run(a-b)
suma, resta

(15, 5)

In [31]:
#varias operacion, dentro de la misma sesion
cte = tf.constant(15)
#Con fill lleno una matriz de x,x, con valor de 10
matriz1 = tf.fill((6,6), 10)
#random nomral, tamaño matriz
matriz2 = tf.random_normal((5,5))
matriz3 = tf.random_uniform((4,4), minval=0, maxval=5)
matriz_ceros = tf.zeros((2,2))
matriz_unos = tf.ones((3,3))


In [34]:
operaciones = [cte, matriz1, matriz2, matriz3, matriz_ceros, matriz_unos]

In [37]:
with tf.Session() as sesion:
  #Dentro de la sesion de tf, ejecutamos.
  #con sesion.run imprimo el resultado de ejecutarlas.
  for i in operaciones:
    print(sesion.run(i))
    print("\n")

15


[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


[[-0.34799865  0.94179773  0.4599604  -1.0791551  -0.24485287]
 [ 0.78849864 -2.932507    0.5005612  -1.975985    0.01189856]
 [ 0.89670545  0.9986326  -1.9421269   0.14161606  0.3630584 ]
 [-0.11134944  0.5554761   0.15401077 -1.0941678   2.0478084 ]
 [ 2.5002935  -0.9740924  -1.1038729   0.95435697  1.054483  ]]


[[0.3806597  0.7569605  1.2591279  0.5122608 ]
 [3.9461775  2.3627174  1.8394595  1.8867433 ]
 [2.116837   1.3494736  1.9444156  4.566595  ]
 [1.3848597  0.1374203  0.34630716 3.2160883 ]]


[[0. 0.]
 [0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


